# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serv.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='serv.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nserv.proto\"\x17\n\x08\x63hek_msg\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x19\n\tchek_stat\x12\x0c\n\x04stat\x18\x01 \x01(\t\"@\n\x10stock_quotes_inp\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0f\n\x07\x65nddate\x18\x02 \x01(\t\x12\r\n\x05tiker\x18\x03 \x01(\t\"J\n\x10stock_quotes_rez\x12\x0c\n\x04\x64\x61te\x18\x01 \x03(\t\x12\r\n\x05\x63lose\x18\x02 \x03(\x01\x12\x0c\n\x04high\x18\x03 \x03(\x01\x12\x0b\n\x03low\x18\x04 \x03(\x01\x32p\n\x10Sender_stock_inf\x12;\n\x11Send_stock_quotes\x12\x11.stock_quotes_inp\x1a\x11.stock_quotes_rez\"\x00\x12\x1f\n\x04\x63hek\x12\t.chek_msg\x1a\n.chek_stat\"\x00\x62\x06proto3'
)




_CHEK_MSG = _descriptor.Descriptor(
  name='chek_msg',
  full_name='chek_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='chek_msg.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=37,
)


_CHEK_STAT = _descriptor.Descriptor(
  name='chek_stat',
  full_name='chek_stat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stat', full_name='chek_stat.stat', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=64,
)


_STOCK_QUOTES_INP = _descriptor.Descriptor(
  name='stock_quotes_inp',
  full_name='stock_quotes_inp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='stock_quotes_inp.date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enddate', full_name='stock_quotes_inp.enddate', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tiker', full_name='stock_quotes_inp.tiker', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=130,
)


_STOCK_QUOTES_REZ = _descriptor.Descriptor(
  name='stock_quotes_rez',
  full_name='stock_quotes_rez',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='stock_quotes_rez.date', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='close', full_name='stock_quotes_rez.close', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='high', full_name='stock_quotes_rez.high', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='low', full_name='stock_quotes_rez.low', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=206,
)

DESCRIPTOR.message_types_by_name['chek_msg'] = _CHEK_MSG
DESCRIPTOR.message_types_by_name['chek_stat'] = _CHEK_STAT
DESCRIPTOR.message_types_by_name['stock_quotes_inp'] = _STOCK_QUOTES_INP
DESCRIPTOR.message_types_by_name['stock_quotes_rez'] = _STOCK_QUOTES_REZ
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

chek_msg = _reflection.GeneratedProtocolMessageType('chek_msg', (_message.Message,), {
  'DESCRIPTOR' : _CHEK_MSG,
  '__module__' : 'serv_pb2'
  # @@protoc_insertion_point(class_scope:chek_msg)
  })
_sym_db.RegisterMessage(chek_msg)

chek_stat = _reflection.GeneratedProtocolMessageType('chek_stat', (_message.Message,), {
  'DESCRIPTOR' : _CHEK_STAT,
  '__module__' : 'serv_pb2'
  # @@protoc_insertion_point(class_scope:chek_stat)
  })
_sym_db.RegisterMessage(chek_stat)

stock_quotes_inp = _reflection.GeneratedProtocolMessageType('stock_quotes_inp', (_message.Message,), {
  'DESCRIPTOR' : _STOCK_QUOTES_INP,
  '__module__' : 'serv_pb2'
  # @@protoc_insertion_point(class_scope:stock_quotes_inp)
  })
_sym_db.RegisterMessage(stock_quotes_inp)

stock_quotes_rez = _reflection.GeneratedProtocolMessageType('stock_quotes_rez', (_message.Message,), {
  'DESCRIPTOR' : _STOCK_QUOTES_REZ,
  '__module__' : 'serv_pb2'
  # @@protoc_insertion_point(class_scope:stock_quotes_rez)
  })
_sym_db.RegisterMessage(stock_quotes_rez)



_SENDER_STOCK_INF = _descriptor.ServiceDescriptor(
  name='Sender_stock_inf',
  full_name='Sender_stock_inf',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=208,
  serialized_end=320,
  methods=[
  _descriptor.MethodDescriptor(
    name='Send_stock_quotes',
    full_name='Sender_stock_inf.Send_stock_quotes',
    index=0,
    containing_service=None,
    input_type=_STOCK_QUOTES_INP,
    output_type=_STOCK_QUOTES_REZ,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='chek',
    full_name='Sender_stock_inf.chek',
    index=1,
    containing_service=None,
    input_type=_CHEK_MSG,
    output_type=_CHEK_STAT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENDER_STOCK_INF)

DESCRIPTOR.services_by_name['Sender_stock_inf'] = _SENDER_STOCK_INF

# @@protoc_insertion_point(module_scope)
